/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XkucharpAmbulanceEmployeesList {
    }
}
declare global {
    interface HTMLXkucharpAmbulanceEmployeesListElement extends Components.XkucharpAmbulanceEmployeesList, HTMLStencilElement {
    }
    var HTMLXkucharpAmbulanceEmployeesListElement: {
        prototype: HTMLXkucharpAmbulanceEmployeesListElement;
        new (): HTMLXkucharpAmbulanceEmployeesListElement;
    };
    interface HTMLElementTagNameMap {
        "xkucharp-ambulance-employees-list": HTMLXkucharpAmbulanceEmployeesListElement;
    }
}
declare namespace LocalJSX {
    interface XkucharpAmbulanceEmployeesList {
    }
    interface IntrinsicElements {
        "xkucharp-ambulance-employees-list": XkucharpAmbulanceEmployeesList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xkucharp-ambulance-employees-list": LocalJSX.XkucharpAmbulanceEmployeesList & JSXBase.HTMLAttributes<HTMLXkucharpAmbulanceEmployeesListElement>;
        }
    }
}
